/* This file has been generated from /home/dragonfly/paparazzi_new/test/paparazzi3/conf/airframes/blade_mdm.xml */
/* Please DO NOT EDIT */

#ifndef AIRFRAME_H
#define AIRFRAME_H 

#define AIRFRAME_NAME "blademdm"
#define AC_ID 32

#define SERVOS_NB 5

#define SERVO_GAZ 4
#define SERVO_GAZ_NEUTRAL 1000
#define SERVO_GAZ_TRAVEL_UP 0.104166666667
#define SERVO_GAZ_TRAVEL_DOWN 0
#define SERVO_GAZ_MAX 2000
#define SERVO_GAZ_MIN 1000

#define SERVO_AILERON 0
#define SERVO_AILERON_NEUTRAL 1600
#define SERVO_AILERON_TRAVEL_UP -0.0416666666667
#define SERVO_AILERON_TRAVEL_DOWN -0.0416666666667
#define SERVO_AILERON_MAX 2000
#define SERVO_AILERON_MIN 1200

#define SERVO_ELEVATOR 1
#define SERVO_ELEVATOR_NEUTRAL 1600
#define SERVO_ELEVATOR_TRAVEL_UP -0.0416666666667
#define SERVO_ELEVATOR_TRAVEL_DOWN -0.0416666666667
#define SERVO_ELEVATOR_MAX 2000
#define SERVO_ELEVATOR_MIN 1200

#define SERVO_RUDDER 2
#define SERVO_RUDDER_NEUTRAL 1530
#define SERVO_RUDDER_TRAVEL_UP -0.0322916666667
#define SERVO_RUDDER_TRAVEL_DOWN -0.0297916666667
#define SERVO_RUDDER_MAX 1816
#define SERVO_RUDDER_MIN 1220


#define COMMAND_THROTTLE 0
#define COMMAND_ROLL 1
#define COMMAND_PITCH 2
#define COMMAND_YAW 3
#define COMMANDS_NB 4
#define COMMANDS_FAILSAFE {0,0,0,0}


#define SetCommandsFromRC(commands) { \
  commands[COMMAND_THROTTLE] = rc_values[RADIO_THROTTLE];\
  commands[COMMAND_ROLL] = rc_values[RADIO_ROLL];\
  commands[COMMAND_PITCH] = rc_values[RADIO_PITCH];\
  commands[COMMAND_YAW] = rc_values[RADIO_YAW];\
}

#define SECTION_MIXER 1
#define AILERON_DIFF 0.66
#define COMBI_SWITCH 1.0
#define PTCH_of_THRT -0.05

#define SetActuatorsFromCommands(values) { \
  uint16_t servo_value;\
  float command_value;\
  command_value = values[COMMAND_THROTTLE];\
  command_value *= command_value>0 ? SERVO_GAZ_TRAVEL_UP : SERVO_GAZ_TRAVEL_DOWN;\
  servo_value = SERVO_GAZ_NEUTRAL + (int16_t)(command_value);\
  actuators[SERVO_GAZ] = ChopServo(servo_value, SERVO_GAZ_MIN, SERVO_GAZ_MAX);\
\
  Actuator(SERVO_GAZ) = SERVOS_TICS_OF_USEC(actuators[SERVO_GAZ]);\
\
  command_value = values[COMMAND_ROLL];\
  command_value *= command_value>0 ? SERVO_AILERON_TRAVEL_UP : SERVO_AILERON_TRAVEL_DOWN;\
  servo_value = SERVO_AILERON_NEUTRAL + (int16_t)(command_value);\
  actuators[SERVO_AILERON] = ChopServo(servo_value, SERVO_AILERON_MIN, SERVO_AILERON_MAX);\
\
  Actuator(SERVO_AILERON) = SERVOS_TICS_OF_USEC(actuators[SERVO_AILERON]);\
\
  command_value = values[COMMAND_PITCH];\
  command_value *= command_value>0 ? SERVO_ELEVATOR_TRAVEL_UP : SERVO_ELEVATOR_TRAVEL_DOWN;\
  servo_value = SERVO_ELEVATOR_NEUTRAL + (int16_t)(command_value);\
  actuators[SERVO_ELEVATOR] = ChopServo(servo_value, SERVO_ELEVATOR_MIN, SERVO_ELEVATOR_MAX);\
\
  Actuator(SERVO_ELEVATOR) = SERVOS_TICS_OF_USEC(actuators[SERVO_ELEVATOR]);\
\
  command_value = values[COMMAND_YAW];\
  command_value *= command_value>0 ? SERVO_RUDDER_TRAVEL_UP : SERVO_RUDDER_TRAVEL_DOWN;\
  servo_value = SERVO_RUDDER_NEUTRAL + (int16_t)(command_value);\
  actuators[SERVO_RUDDER] = ChopServo(servo_value, SERVO_RUDDER_MIN, SERVO_RUDDER_MAX);\
\
  Actuator(SERVO_RUDDER) = SERVOS_TICS_OF_USEC(actuators[SERVO_RUDDER]);\
\
  ActuatorsCommit();\
}
#define SECTION_adc 1
#define ADC_CHANNEL_IR1 1
#define ADC_CHANNEL_IR2 0
#define ADC_CHANNEL_IR_NB_SAMPLES 16
#define ADC_CHANNEL_GYRO_ROLL 2
#define ADC_CHANNEL_GYRO_PITCH 3
#define ADC_CHANNEL_GYRO_NB_SAMPLES 16
#define ADC_CHANNEL_ACCEL_AX 6
#define ADC_CHANNEL_ACCEL_AY 5
#define ADC_CHANNEL_ACCEL_AZ 4
#define ADC_CHANNEL_ACCEL_NB_SAMPLES 16

#define SECTION_AUTO1 1
#define AUTO1_MAX_ROLL RadOfDeg(40)
#define AUTO1_MAX_PITCH RadOfDeg(40)

#define SECTION_INFRARED 1
#define IR_ROLL_NEUTRAL_DEFAULT 6.3
#define IR_PITCH_NEUTRAL_DEFAULT -61
#define IR_DEFAULT_CONTRAST 900
#define IR_RAD_OF_IR_CONTRAST 1.7
#define IR_RollOfIrs(x1,x2) (0.7*(x1)+ -0.7*(x2))
#define IR_PitchOfIrs(x1,x2) (-0.7*(x1)+ -0.7*(x2))
#define IR_RAD_OF_IR_MAX_VALUE 0.0045
#define IR_RAD_OF_IR_MIN_VALUE 0.00075
#define IR_ADC_ROLL_NEUTRAL 0
#define IR_ADC_PITCH_NEUTRAL 0
#define IR_ESTIMATED_PHI_PI_4 M_PI_4
#define IR_CORRECTION_UP 1.
#define IR_CORRECTION_DOWN 1.
#define IR_CORRECTION_LEFT 1.
#define IR_CORRECTION_RIGHT 1.

#define SECTION_GYRO 1
#define GYRO_ADC_ROLL_NEUTRAL 329
#define GYRO_ADC_PITCH_NEUTRAL 276
#define GYRO_ROLL_SCALE 3.07
#define GYRO_ROLL_DIRECTION -1
#define GYRO_PITCH_SCALE 2.52
#define GYRO_PITCH_DIRECTION 1.

#define SECTION_ACCEL 1
#define ACCEL_AX_NEUTRAL 327
#define ACCEL_AY_NEUTRAL 667
#define ACCEL_AZ_NEUTRAL 658
#define ACCEL_AX_SCALE 0.03
#define ACCEL_AY_SCALE 0.03
#define ACCEL_AZ_SCALE 0.03

#define SECTION_BAT 1
#define MILLIAMP_PER_PERCENT 0.86
#define VOLTAGE_ADC_A 0.0177531
#define VOLTAGE_ADC_B 0.173626
#define VoltageOfAdc(adc) (VOLTAGE_ADC_A * adc+VOLTAGE_ADC_B)
#define LOW_BATTERY 9.3

#define SECTION_VERTICAL CONTROL 1
#define V_CTL_ALTITUDE_PGAIN -0.085
#define V_CTL_ALTITUDE_MAX_CLIMB 2.
#define V_CTL_AUTO_THROTTLE_PGAIN -0.021
#define V_CTL_AUTO_THROTTLE_IGAIN 0.0
#define V_CTL_AUTO_THROTTLE_PITCH_OF_VZ_PGAIN 0.05
#define V_CTL_AUTO_THROTTLE_DASH_TRIM -1000
#define V_CTL_AUTO_THROTTLE_LOITER_TRIM 1500
#define V_CTL_AUTO_THROTTLE_CRUISE_THROTTLE 0.60
#define V_CTL_AUTO_THROTTLE_NOMINAL_CRUISE_THROTTLE 0.60
#define V_CTL_AUTO_THROTTLE_CLIMB_THROTTLE_INCREMENT 0.07
#define V_CTL_AUTO_PITCH_PGAIN -0.1
#define V_CTL_AUTO_PITCH_IGAIN 0.0
#define V_CTL_AUTO_PITCH_MAX_PITCH 0.35
#define V_CTL_AUTO_PITCH_MIN_PITCH -0.35
#define V_CTL_THROTTLE_SLEW 0.05

#define SECTION_HORIZONTAL CONTROL 1
#define H_CTL_COURSE_PGAIN 0.12
#define H_CTL_ROLL_MAX_SETPOINT 0.6
#define H_CTL_PITCH_MAX_SETPOINT 0.5
#define H_CTL_PITCH_MIN_SETPOINT -0.5
#define H_CTL_ROLL_PGAIN -12000.
#define H_CTL_AILERON_OF_THROTTLE 0.0
#define H_CTL_PITCH_PGAIN -8000.
#define H_CTL_PITCH_DGAIN 0.0
#define H_CTL_ELEVATOR_OF_ROLL 2250
#define H_CTL_ROLL_RATE_MODE_DEFAULT 1
#define H_CTL_ROLL_RATE_SETPOINT_PGAIN 6.0
#define H_CTL_ROLL_RATE_MAX_SETPOINT 10
#define H_CTL_LO_THROTTLE_ROLL_RATE_PGAIN 1700.
#define H_CTL_HI_THROTTLE_ROLL_RATE_PGAIN 1400.
#define H_CTL_ROLL_RATE_IGAIN 0.
#define H_CTL_ROLL_RATE_DGAIN 0.
#define H_CTL_ROLL_RATE_SUM_NB_SAMPLES 64

#define SECTION_THR 1
#define DASH_THR 1.0
#define LOITER_THR 0.50

#define SECTION_NAV 1
#define NAV_PITCH 0.
#define NAV_GLIDE_PITCH_TRIM 0

#define SECTION_AGGRESSIVE 1
#define AGR_BLEND_START 20
#define AGR_BLEND_END 10
#define AGR_CLIMB_THROTTLE 0.95
#define AGR_CLIMB_PITCH 0.3
#define AGR_DESCENT_THROTTLE 0.1
#define AGR_DESCENT_PITCH -0.25
#define AGR_CLIMB_NAV_RATIO 0.8
#define AGR_DESCENT_NAV_RATIO 1.0

#define SECTION_MISC 1
#define NOMINAL_AIRSPEED 10.
#define CARROT 5.
#define KILL_MODE_DISTANCE (MAX_DIST_FROM_HOME*1.5)
#define XBEE_INIT "ATPL4\rATRN1\rATTT80\rATBD3\rATWR\r"
#define NO_XBEE_API_INIT TRUE
#define UNLOCKED_HOME_MODE TRUE
#define RC_LOST_MODE PPRZ_MODE_AUTO2

#define SECTION_GYRO 1
#define GYRO_MAX_RATE 500.
#define ROLLRATESUM_NB_SAMPLES 60
#define ALT_ROLL_PGAIN 5.5
#define ROLL_RATE_PGAIN 860.0
#define ROLL_RATE_IGAIN 0.0
#define ROLL_RATE_DGAIN 0.0
#define CONFIDENCE_COEFF 34.0
#define J_FILTER 0

#define SECTION_SIMU 1
#define ROLL_RESPONSE_FACTOR 60.
#define YAW_RESPONSE_FACTOR 0.6
#define WEIGHT 1.280

#define SECTION_FAILSAFE 1
#define FAILSAFE_DELAY_WITHOUT_GPS 2
#define FAILSAFE_DEFAULT_THROTTLE 0.1
#define FAILSAFE_DEFAULT_ROLL 0.3
#define FAILSAFE_DEFAULT_PITCH 0.08
#define FAILSAFE_HOME_RADIUS 50

#define SECTION_CAM 1
#define CAM_THETA0 0
#define CAM_PHI0 0

#define SECTION_DATALINK 1
#define DATALINK_DEVICE_TYPE XBEE
#define DATALINK_DEVICE_ADDRESS ....


#endif // AIRFRAME_H
