/* This file has been generated from /home/dragonfly/paparazzi_new/test/paparazzi3/conf/airframes/plaster1.xml */
/* Please DO NOT EDIT */

#ifndef AIRFRAME_H
#define AIRFRAME_H 

#define AIRFRAME_NAME "Plaster"
#define AC_ID 2

#define SECTION_adc 1
#define ADC_CHANNEL_IR1 1
#define ADC_CHANNEL_IR2 0
#define ADC_CHANNEL_VSUPPLY 3
#define ADC_CHANNEL_IR_NB_SAMPLES 16

#define SERVOS_NB 7

#define SERVO_GAZ 0
#define SERVO_GAZ_NEUTRAL 1000
#define SERVO_GAZ_TRAVEL_UP 0.078125
#define SERVO_GAZ_TRAVEL_DOWN 0
#define SERVO_GAZ_MAX 1750
#define SERVO_GAZ_MIN 1000

#define SERVO_AILEVON_RIGHT 2
#define SERVO_AILEVON_RIGHT_NEUTRAL 1480
#define SERVO_AILEVON_RIGHT_TRAVEL_UP -0.0291666666667
#define SERVO_AILEVON_RIGHT_TRAVEL_DOWN -0.0333333333333
#define SERVO_AILEVON_RIGHT_MAX 1800
#define SERVO_AILEVON_RIGHT_MIN 1200

#define SERVO_AILEVON_LEFT 6
#define SERVO_AILEVON_LEFT_NEUTRAL 1440
#define SERVO_AILEVON_LEFT_TRAVEL_UP -0.025
#define SERVO_AILEVON_LEFT_TRAVEL_DOWN -0.0375
#define SERVO_AILEVON_LEFT_MAX 1800
#define SERVO_AILEVON_LEFT_MIN 1200


#define COMMAND_THROTTLE 0
#define COMMAND_ROLL 1
#define COMMAND_PITCH 2
#define COMMANDS_NB 3
#define COMMANDS_FAILSAFE {0,0,0}


#define SetCommandsFromRC(commands) { \
  commands[COMMAND_THROTTLE] = rc_values[RADIO_THROTTLE];\
  commands[COMMAND_ROLL] = rc_values[RADIO_ROLL];\
  commands[COMMAND_PITCH] = rc_values[RADIO_PITCH];\
}

#define SetActuatorsFromCommands(values) { \
  uint16_t servo_value;\
  float command_value;\
  command_value = values[COMMAND_THROTTLE];\
  command_value *= command_value>0 ? SERVO_GAZ_TRAVEL_UP : SERVO_GAZ_TRAVEL_DOWN;\
  servo_value = SERVO_GAZ_NEUTRAL + (int16_t)(command_value);\
  actuators[SERVO_GAZ] = ChopServo(servo_value, SERVO_GAZ_MIN, SERVO_GAZ_MAX);\
\
  Actuator(SERVO_GAZ) = SERVOS_TICS_OF_USEC(actuators[SERVO_GAZ]);\
\
  int16_t _var_aileron = values[COMMAND_ROLL] * AILEVON_AILERON_RATE;\
  int16_t _var_elevator = values[COMMAND_PITCH] * AILEVON_ELEVATOR_RATE;\
  command_value = _var_aileron + _var_elevator;\
  command_value *= command_value>0 ? SERVO_AILEVON_LEFT_TRAVEL_UP : SERVO_AILEVON_LEFT_TRAVEL_DOWN;\
  servo_value = SERVO_AILEVON_LEFT_NEUTRAL + (int16_t)(command_value);\
  actuators[SERVO_AILEVON_LEFT] = ChopServo(servo_value, SERVO_AILEVON_LEFT_MIN, SERVO_AILEVON_LEFT_MAX);\
\
  Actuator(SERVO_AILEVON_LEFT) = SERVOS_TICS_OF_USEC(actuators[SERVO_AILEVON_LEFT]);\
\
  command_value = _var_aileron - _var_elevator;\
  command_value *= command_value>0 ? SERVO_AILEVON_RIGHT_TRAVEL_UP : SERVO_AILEVON_RIGHT_TRAVEL_DOWN;\
  servo_value = SERVO_AILEVON_RIGHT_NEUTRAL + (int16_t)(command_value);\
  actuators[SERVO_AILEVON_RIGHT] = ChopServo(servo_value, SERVO_AILEVON_RIGHT_MIN, SERVO_AILEVON_RIGHT_MAX);\
\
  Actuator(SERVO_AILEVON_RIGHT) = SERVOS_TICS_OF_USEC(actuators[SERVO_AILEVON_RIGHT]);\
\
  ActuatorsCommit();\
}
#define SECTION_MIXER 1
#define AILEVON_AILERON_RATE 0.55
#define AILEVON_ELEVATOR_RATE 0.75

#define SECTION_AUTO1 1
#define AUTO1_MAX_ROLL 0.8
#define AUTO1_MAX_PITCH 0.6

#define SECTION_INFRARED 1
#define IR_ROLL_NEUTRAL_DEFAULT -4.3
#define IR_PITCH_NEUTRAL_DEFAULT 3
#define IR_DEFAULT_CONTRAST 400
#define IR_RAD_OF_IR_CONTRAST 0.6
#define IR_RAD_OF_IR_MIN_VALUE 0.0008
#define IR_RAD_OF_IR_MAX_VALUE 0.008
#define IR_RollOfIrs(i1, i2) (-i1 -i2)
#define IR_PitchOfIrs(i1, i2) (i2-i1)
#define IR_ADC_ROLL_NEUTRAL -1042
#define IR_ADC_PITCH_NEUTRAL 10

#define SECTION_PID 1
#define ROLL_PGAIN 6000.
#define PITCH_OF_ROLL 0.2
#define PITCH_PGAIN 9000.
#define MAX_ROLL 0.4
#define MAX_PITCH 0.25
#define MIN_PITCH -0.35
#define AILERON_OF_GAZ -0.13
#define CRUISE_THROTTLE 0.50

#define SECTION_ALT 1
#define CLIMB_PITCH_PGAIN -0.1
#define CLIMB_PITCH_IGAIN 1.0
#define CLIMB_PGAIN -0.025
#define CLIMB_IGAIN 0.01
#define CLIMB_MAX 1.
#define CLIMB_GAZ_OF_CLIMB 0.15
#define CLIMB_PITCH_OF_VZ_PGAIN 0.1

#define SECTION_NAV 1
#define COURSE_PGAIN -0.2
#define ALTITUDE_PGAIN -0.05
#define NAV_PITCH 0.
#define NAV_GLIDE_PITCH_TRIM 0

#define SECTION_BAT 1
#define MILLIAMP_PER_PERCENT 1.24
#define VOLTAGE_ADC_A 0.01727
#define VOLTAGE_ADC_B 0.2965
#define VoltageOfAdc(adc) (VOLTAGE_ADC_A * adc + VOLTAGE_ADC_B)
#define LOW_BATTERY 9

#define SECTION_SERVOS 1
#define SERVOS_VOLTAGE_ADC_A 0.005661
#define SERVOS_VOLTAGE_ADC_B 0.014948
#define ServosVoltageOfAdc(adc) (VOLTAGE_ADC_A * adc + VOLTAGE_ADC_B)

#define SECTION_VERTICAL CONTROL 1
#define V_CTL_ALTITUDE_PGAIN 0.3
#define V_CTL_ALTITUDE_MAX_CLIMB 2.
#define V_CTL_AUTO_THROTTLE_MIN_CRUISE_THROTTLE 0.35
#define V_CTL_AUTO_THROTTLE_MAX_CRUISE_THROTTLE 0.45
#define V_CTL_AUTO_THROTTLE_PGAIN 0.02
#define V_CTL_AUTO_THROTTLE_IGAIN 0.0
#define V_CTL_AUTO_THROTTLE_PITCH_OF_VZ_PGAIN 0.0
#define V_CTL_AUTO_THROTTLE_DASH_TRIM 1000
#define V_CTL_AUTO_THROTTLE_LOITER_TRIM 1500
#define V_CTL_AUTO_THROTTLE_CRUISE_THROTTLE 0.488
#define V_CTL_AUTO_THROTTLE_CRUISE_THROTTLE_PGAIN 0.01
#define V_CTL_AUTO_THROTTLE_NOMINAL_CRUISE_THROTTLE 0.47
#define V_CTL_AUTO_THROTTLE_CLIMB_THROTTLE_INCREMENT 0.02
#define V_CTL_THROTTLE_SUM_NB_SAMPLES 32
#define V_CTL_AUTO_PITCH_PGAIN 0.1
#define V_CTL_AUTO_PITCH_IGAIN 0.0
#define V_CTL_AUTO_PITCH_MAX_PITCH 0.35
#define V_CTL_AUTO_PITCH_MIN_PITCH -0.35
#define V_CTL_VDROP2THROTTLE 0
#define V_CTL_THROTTLE_SLEW 1.0

#define SECTION_HORIZONTAL CONTROL 1
#define H_CTL_COURSE_PGAIN 0.5
#define H_CTL_ROLL_MAX_SETPOINT RadOfDeg(45)
#define H_CTL_PITCH_MAX_SETPOINT RadOfDeg(30)
#define H_CTL_PITCH_MIN_SETPOINT RadOfDeg(-20)
#define H_CTL_YAW_MAX_SETPOINT RadOfDeg(20)
#define H_CTL_ROLL_PGAIN -12000.
#define H_CTL_AILERON_OF_THROTTLE 0.0
#define H_CTL_PITCH_PGAIN 11950.
#define H_CTL_PITCH_DGAIN 0.0
#define H_CTL_ELEVATOR_OF_ROLL 0.
#define H_CTL_ROLL_RATE_MODE_DEFAULT 1
#define H_CTL_PITCH_RATE_MODE_DEFAULT 1
#define H_CTL_YAW_RATE_MODE_DEFAULT 1
#define H_CTL_ROLL_RATE_SETPOINT_PGAIN 0.75
#define H_CTL_ROLL_RATE_MAX_SETPOINT 10
#define H_CTL_PITCH_RATE_SETPOINT_PGAIN 0.75
#define H_CTL_PITCH_RATE_MAX_SETPOINT 10
#define H_CTL_YAW_RATE_SETPOINT_PGAIN 0.75
#define H_CTL_YAW_RATE_MAX_SETPOINT 10
#define H_CTL_LO_THROTTLE_ROLL_RATE_PGAIN 25000.
#define H_CTL_HI_THROTTLE_ROLL_RATE_PGAIN 25000.
#define H_CTL_LO_THROTTLE_PITCH_RATE_PGAIN 13000.
#define H_CTL_HI_THROTTLE_PITCH_RATE_PGAIN 13000.
#define H_CTL_LO_THROTTLE_YAW_RATE_PGAIN 18000.
#define H_CTL_HI_THROTTLE_YAW_RATE_PGAIN 18000.
#define H_CTL_ROLL_RATE_IGAIN 0.
#define H_CTL_ROLL_RATE_DGAIN 0.
#define H_CTL_ROLL_RATE_SUM_NB_SAMPLES 16
#define H_CTL_PITCH_RATE_IGAIN 0.
#define H_CTL_PITCH_RATE_DGAIN 0.
#define H_CTL_PITCH_RATE_SUM_NB_SAMPLES 16
#define H_CTL_YAW_RATE_IGAIN 0.
#define H_CTL_YAW_RATE_DGAIN 0.
#define H_CTL_YAW_RATE_SUM_NB_SAMPLES 16

#define SECTION_MISC 1
#define NOMINAL_AIRSPEED 12.
#define CARROT 5.
#define KILL_MODE_DISTANCE (MAX_DIST_FROM_HOME*1.5)

#define SECTION_SIMU 1
#define ROLL_RESPONSE_FACTOR 14.
#define YAW_RESPONSE_FACTOR 1.
#define WEIGHT 0.3

#define SECTION_FAILSAFE 1
#define FAILSAFE_DELAY_WITHOUT_GPS 2
#define FAILSAFE_DEFAULT_GAZ CRUISE_THROTTLE+0.05
#define FAILSAFE_DEFAULT_ROLL 0.17
#define FAILSAFE_DEFAULT_PITCH 0.08
#define FAILSAFE_HOME_RADIUS 50
#define FAILSAFE_DEFAULT_THROTTLE 0.2

#define SECTION_CAM 1
#define CAM_THETA0 45
#define CAM_PHI0 -45

#define SECTION_DATALINK 1
#define DATALINK_DEVICE_TYPE XBEE
#define DATALINK_DEVICE_ADDRESS 

#define SECTION_AGGRESSIVE 1
#define AGR_CLIMB_GAZ 0.8
#define AGR_DESCENT_GAZ 0.1
#define AGR_CLIMB_PITCH 0.2
#define AGR_DESCENT_PITCH -0.2
#define AGR_BLEND_START 15
#define AGR_BLEND_END 8
#define AGR_CLIMB_NAV_RATIO 0.8
#define AGR_DESCENT_NAV_RATIO 1.0


#endif // AIRFRAME_H
